controller_list:
  - name: yumi/egm/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - yumi_robl_joint_1
      - yumi_robl_joint_2
      - yumi_robl_joint_3
      - yumi_robl_joint_4
      - yumi_robl_joint_5
      - yumi_robl_joint_6
      - yumi_robl_joint_7
      - yumi_robr_joint_1
      - yumi_robr_joint_2
      - yumi_robr_joint_3
      - yumi_robr_joint_4
      - yumi_robr_joint_5
      - yumi_robr_joint_6
      - yumi_robr_joint_7

# controller_list:
#   - name: yumi_l
#     action_ns: joint_controller_l
#     type: FollowJointTrajectory
#     joints:
#       - yumi_robl_joint_1
#       - yumi_robl_joint_2
#       - yumi_robl_joint_3
#       - yumi_robl_joint_4
#       - yumi_robl_joint_5
#       - yumi_robl_joint_6
#       - yumi_robl_joint_7
#   - name: yumi_r
#     action_ns: joint_controller_r
#     type: FollowJointTrajectory
#     joints:
#       - yumi_robr_joint_1
#       - yumi_robr_joint_2
#       - yumi_robr_joint_3
#       - yumi_robr_joint_4
#       - yumi_robr_joint_5
#       - yumi_robr_joint_6
#       - yumi_robr_joint_7
  